name: Documentation Generation

on:
  push:
    branches: [ release, pheonix ]
    paths:
    - 'docs/**'
    - '.requirements/**'
    - '.github/workflows/docs.yaml'
  workflow_dispatch:


jobs:
  build:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest
    steps:
      # https://abbbi.github.io/actions/
      # disables some Ubuntu functionality that we don't need in a "throw away" runtime
      - uses: abbbi/github-actions-tune@v1

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Python
        id: pthon-install
        uses: actions/setup-python@v4
        with:
          # supported versions: https://github.com/actions/python-versions/releases
          python-version: 3.11
          cache: pip
          cache-dependency-path: '.requirements/docs.txt'

      - name: Upgrade Pip, etc
        run: python -m pip install pip setuptools wheel --upgrade

      - name: Install invoke, etc
        run: pip install invoke minchin.text

      # - name: Install pip-tools
      #   run: pip install pip-tools

      # - name: Install requirements (via invoke)
      #   run: invoke upgrade --requirements-file build --verbose

      - name: Install requirements (via pip)
        run: pip install .[docs]

      - name: Build Site
        run: invoke build-docs

      - name: Upload Artifact (Built Site)
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/_build

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
